<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>CtrlCenter</RootNamespace>
    <AssemblyName>CtrlCenter.Wpf</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <!-- SQLite 核心包 -->
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.0" />  
    <!-- ✅ 关键：这个包会自动初始化 SQLitePCL.raw -->    
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="6.0.0" />
	<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />	
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
	<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Management" Version="6.0.0" />
  </ItemGroup>
</Project>
