; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "高压开关试验报表管理平台"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "tomatoyou@139.com"
#define MyAppURL "https://github.com/ShawnWang6/app_center_wpf"
#define MyAppExeName "ReportMaker.exe"
#define MyAppId "{CD5F7178-4144-4199-AB19-D0D488282A2B}"
[Setup]
AppId={{CD5F7178-4144-4199-AB19-D0D488282A2B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;VersionInfoVersion={#MyAppVersion}
;VersionInfoVersion
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\zhuhaizg\ReportMaker
; DisableProgramGroupPage=yes
DefaultGroupName=珠海正冠科技
; Uncomment the following line to run in non admainistrative install mode (install for current user only.)
;PrivilegesRequired=lowest
;PrivilegesRequired=admin
OutputDir= .\Release
OutputBaseFilename=ReportMakerSetupV{#MyAppVersion}
SetupIconFile=.\publish\app.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
;隐藏安装路径选择页面
DisableDirPage=yes

[Code]
function PosEx(const SubStr, S: String; Offset: Integer): Integer;
var
  I, X: Integer;
  Len, LenSubStr: Integer;
begin
  if Offset < 1 then
    Offset := 1;
  
  Len := Length(S);
  LenSubStr := Length(SubStr);
  
  Result := 0;
  if (LenSubStr = 0) or (Len = 0) or (Len < LenSubStr) then
    Exit;
    
  for I := Offset to Len - LenSubStr + 1 do
  begin
    if S[I] = SubStr[1] then
    begin
      Result := I;
      for X := 2 to LenSubStr do
      begin
        if S[I + X - 1] <> SubStr[X] then
        begin
          Result := 0;
          Break;
        end;
      end;
      if Result <> 0 then
        Exit;
    end;
  end;
end;

function ParseVersion(VersionStr: String; var Major, Minor, Build: Integer): Boolean;
var
  Parts: array of String;
  Temp: String;
  PosDot: Integer;
begin
  Result := True;
  try
    // 初始化数组
    SetArrayLength(Parts, 0);
    Temp := VersionStr;
    
    // 循环分割字符串
    while Pos('.', Temp) > 0 do
    begin
      PosDot := Pos('.', Temp);
      SetArrayLength(Parts, GetArrayLength(Parts) + 1);
      Parts[GetArrayLength(Parts) - 1] := Copy(Temp, 1, PosDot - 1);
      Temp := Copy(Temp, PosDot + 1, Length(Temp));
    end;
    // 添加最后一段
    SetArrayLength(Parts, GetArrayLength(Parts) + 1);
    Parts[GetArrayLength(Parts) - 1] := Temp;

    // 赋值（安全取前3段）
    Major := StrToInt(Parts[0]);
    Minor := StrToInt(Parts[1]);
    if GetArrayLength(Parts) >= 3 then
      Build := StrToInt(Parts[2])
    else
      Build := 0;
  except
    Result := False;
  end;
end;

function CheckUninstallKey(RootKey: Integer; AppId: String; var Version: String): Boolean;
var
  appPath: String;
begin
  appPath := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\' + AppId + '_is1';
  // MsgBox('REG32in32: ' + appPath, mbError, MB_YESNO)
  Result := RegQueryStringValue(RootKey, appPath, 'DisplayVersion', Version);  
  if not Result and IsWin64 then
  begin    
    
	appPath := 'Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\' + AppId + '_is1';
	//MsgBox('REG32in64: ' + appPath, mbError, MB_YESNO)
    Result := RegQueryStringValue(RootKey, appPath, 'DisplayVersion', Version);
  end;
end;



function MutexExists(const MutexName: string): Boolean;
begin
   if CheckForMutexes(MutexName) then
   begin    
    Result := True;
    Exit;
   end;  
   Result := False;
end;

// ============ 新增：检查是否为升级安装 ============
function IsUpgradeInstall(): Boolean;
var
  AppGuid: String;
  installedVersion: String;
begin
  AppGuid := '{#MyAppId}';
  Result := CheckUninstallKey(HKLM, AppGuid, installedVersion) or
            CheckUninstallKey(HKCU, AppGuid, installedVersion);
end;

function InitializeSetup(): Boolean;
var
  AppGuid: String;
  installedVersion: String;
  majorNew, minorNew, buildNew: Integer;
  majorOld, minorOld, buildOld: Integer;
begin
  Result := True;  
    
  
  if MutexExists('Global\__?ReportMaker2026?__') then
  begin
	MsgBox('目标程序[{#SetupSetting("AppName")}]正在运行，安装前必须关闭它。', mbError, MB_OK);	
    Result := False;
	Exit;
  end;
  
  // 检查所有可能的注册表位置 
  AppGuid := '{#MyAppId}';
  if CheckUninstallKey(HKLM, AppGuid, installedVersion) or
     CheckUninstallKey(HKCU, AppGuid, installedVersion) then
  begin
	// MsgBox('检测到已安装版本 (' + installedVersion + ') 当前版本 '+ '{#SetupSetting("AppVersion")}', mbError, MB_YESNO)
	ParseVersion(installedVersion, majorOld, minorOld, buildOld);
    ParseVersion('{#SetupSetting("AppVersion")}', majorNew, minorNew, buildNew);
	 // 比较版本号
    if (majorOld > majorNew) or
       ((majorOld = majorNew) and (minorOld > minorNew)) or
       ((majorOld = majorNew) and (minorOld = minorNew) and (buildOld > buildNew)) then
    begin
      if MsgBox('检测到已安装更新版本 (' + installedVersion + ')。' + #13#10 +
                '当前安装版本: {#SetupSetting("AppVersion")}' + #13#10 +
                '继续安装旧版本可能导致兼容性问题。' + #13#10 +
                '是否仍要继续安装？', mbError, MB_YESNO) = IDNO then
      begin
        Result := False;
      end;
    end;
  end;
end;

// ============ 新增：在文件复制完成后执行配置复制 ============
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
  end;
end;


[Languages]
;Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 将你的WPF程序输出目录下的所有文件都打包进去
; 请将 "..\YourWpfApp\bin\Release\net8.0-windows\publish\" 替换为你实际的发布路径
; Source: "..\YourWpfApp\bin\Release\net8.0-windows\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

Source: ".\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
; Source: ".\publish\\appsetting.json"; DestDir: "{app}"; Flags: onlyifdoesntexist
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\珠海正冠科技\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}" ; IconFilename: "{app}\app.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser